# Generated by Django 4.1.3 on 2022-11-19 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='region',
        ),
    ]
