# Generated by Django 4.1.3 on 2022-11-07 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image_name_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='url',
        ),
    ]
