# Generated by Django 4.1.3 on 2023-01-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_state_city_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
